[package]
name = "msg_bgm"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prc-rs = { git = "https://github.com/ultimate-research/prc-rs.git" }
hash40 = "*"
